spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./shiro
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
server:
  port: 8080

logging:
  level:
    org.jooq.tools.LoggerListener: debug
