spring:
  profiles:
    active: dev
  # session会话存储类型
  session:
    store-type: hash_map
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      exclude: templates/**,static/**

logging:
  level:
    org.hibernate.SQL: debug

server:
  error:
    whitelabel:
      enabled: false
