spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xunwu?characterEncoding=utf-8&useSSL=false
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      location: D:/
      file-size-threshold: 5MB
      max-request-size: 20MB