spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test
    username: root
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none