spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./dangdang-spider.sqlite3
    username:
    password:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
      dangdang:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:14306/dangdang?characterEncoding=utf-8&useSSL=false
        username: dataway-rw
        password: QqHVMhmN*8
      h2test:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./dangdang;MODE=MYSQL;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;INIT=RUNSCRIPT FROM 'classpath:schema.sql'
        username: sa
        password:
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.jooq.tools.LoggerListener: debug
