spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:7306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
#server:
#  servlet:
#    context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: C:\Users\DELL\Documents\
#  file: C:\Users\DELL\Documents\sell.log
#  level:
#    com.danyl.LoggerTest: debug


wechat:
  mpAppId: wx4e9217ae75fdeb45
  mpAppSecret: 82c220262b6b80947dab6fa969e41fe5

  openAppId: wx4e9217ae75fdeb45
  openAppSecret: 82c220262b6b80947dab6fa969e41fe5

  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://danyl.natappvip.cc/sell/pay/notify
