spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./spiders;MODE=MYSQL;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;MVCC=TRUE;
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql

    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true