spring:
  datasource:
    druid:
      dangdang:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:14306/dangdang?characterEncoding=utf-8&useSSL=false
        username: dataway-rw
        password: QqHVMhmN*8
      new-vip:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:14306/new_vip?characterEncoding=utf-8&useSSL=false
        username: dataway-rw
        password: QqHVMhmN*8
      xiaomi:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:14306/xiaomi?characterEncoding=utf-8&useSSL=false
        username: dataway-rw
        password: QqHVMhmN*8
logging:
  level:
    org.jooq.tools.LoggerListener: debug

webdriver:
  driver-map:
    webdriver.chrome.driver: 'C:/Users/DELL/AppData/Local/360Chrome/Chrome/Application/chromedriver.exe'
    phantomjs.binary.path: 'D:/360极速浏览器下载/phantomjs-2.1.1-windows/bin/phantomjs.exe'