spring:
  datasource:
    druid:
      dangdang:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.14:13306/dangdang?characterEncoding=utf-8&useSSL=false
        username: dataway-rw
        password: QqHVMhmN*8
      new-vip:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.14:13306/new_vip?characterEncoding=utf-8&useSSL=false
        username: dataway-rw
        password: QqHVMhmN*8
      xiaomi:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.14:13306/xiaomi?characterEncoding=utf-8&useSSL=false
        username: dataway-rw
        password: QqHVMhmN*8
logging:
  level:
    org.jooq.tools.LoggerListener: info

webdriver:
  driver-map:
    phantomjs.binary.path: '/usr/bin/phantomjs'